version: "3"
services:
  rpc-proxy:
    container_name: rpc-proxy
    image: dobtc/btc-rpc-proxy
    ports:
      - 8331:8331
    volumes:
      - /path/to/config/btc_rpc_proxy.toml:/etc/btc_rpc_proxy.toml
